language: ruby
rvm: # http://rubies.travis-ci.org/
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
env:
  - WITH_LIBXML=true
  - WITH_LIBXML=false
before_script: |
  if [[ "$WITH_LIBXML" == "true" ]]; then
    # OS X doesn't have libxml by default, so install it
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install libxml2
    fi
  # WITH_LIBXML=false
  else
    # Ubuntu/Linux has libxml installed by default, so remove it
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get remove libxml2-dev
    fi
  fi
os:
  - linux
  - osx
